### ISSUE TITLE
Use of -r when making binutils

### ISSUE THREAD

**Issue by harrysarson** [physical-computation/Sunflower-toolchain#19]
On this line of the Makefile we pass `-r` to make.

https://github.com/phillipstanleymarbell/Sunflower-toolchain/blob/b74c5dc3457adf86fe428605fac176f639022b1d/tools/Makefile#L24

The `-r` argument is [documented as follows](https://www.gnu.org/software/make/manual/make.html)

> ‘-r’
> ‘--no-builtin-rules’
>
>    Eliminate use of the built-in implicit rules (see Using Implicit Rules). You can still define your own by writing pattern rules (see Defining and Redefining Pattern Rules). The ‘-r’ option also clears out the default list of suffixes for suffix rules (see Old-Fashioned Suffix Rules). But you can still define your own suffixes with a rule for .SUFFIXES, and then define your own suffix rules. Note that only rules are affected by the -r option; default variables remain in effect (see Variables Used by Implicit Rules); see the ‘-R’ option below.

The build issues mentioned in https://github.com/phillipstanleymarbell/Sunflower-toolchain/pull/18#issuecomment-523886818 and https://github.com/phillipstanleymarbell/Sunflower-toolchain/pull/18#issuecomment-523991239 are fixed if I remove the flag.

@phillipstanleymarbell do you know why the `-r` flag was added?

**Comment by phillipstanleymarbell** [comment]
At some point, on some platform, that was necessary. I'm happy to merge the change. Ideally someone would test on macOS (I'm assuming you're on Linux and I know @SamuelmsWong is testing on Linux).

Let's merge your suggestion anyway.

**Comment by harrysarson** [comment]
Makes sense :+1:

**Comment by harrysarson** [comment]
Changes are included in #18

**Comment by harrysarson** [comment]
Closing as #18 is merged 🎉
