### ISSUE TITLE
Duplicate top level makefile in simulator and toolchain

### ISSUE THREAD

**Issue by harrysarson** [physical-computation/Sunflower-toolchain#20]
Another issue to come out working with Makefile in #18:

The files: https://github.com/physical-computation/sunflower-simulator/blob/master/Makefile and https://github.com/phillipstanleymarbell/Sunflower-toolchain/blob/master/Makefile are almost identical.

I believe the Makefile in `sunflower-simulator` could be made to depend on that in `sunflower-toolchain` to reduce duplication of code.

**Comment by phillipstanleymarbell** [comment]
I agree. @SamuelmsWong, could you look at this at some point?

**Comment by SamuelmsWong-zz** [comment]
I've made a PR for both the simulator and the toolchain repos. I haven't actually tested the build because it would take a while and my changes were quite small.

**Comment by SamuelmsWong-zz** [comment]
The simulator PR is https://github.com/physical-computation/sunflower-simulator/pull/109
